name: Use SPN with OIDC to access Azure
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        # below uses repository secrets available to all workflows in the repository
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
    
      - name: Example of using environment secrets
        env:
          PROD_SECRET1: ${{ secrets.PROD_SECRET2 }}
        run: |
          echo "The production secret is $PROD_SECRET1"