name: Use SPN with OIDC to access Azure
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# global environment variable
# this is available to all jobs in the workflow
# and can be used to pass information  
env:
  MY_ENV: 'prod'
  
jobs:
  oidc-login:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        # below uses repository secrets available to all workflows in the repository
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

  access-environment-secrets:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print ${{ env.MY_ENV }} environment secret
        run: echo "${{ secrets.PROD_SECRET }}"
